### ISSUE TITLE
Invalid register error

### ISSUE THREAD

**Issue by scinos** [ksg97031/frida-gadget#12]
_disclaimer: I'm really new to apk patching, I don't know what I'm doing_

I'm trying to path an app so I can debug it. When I use

```
frida-gadget base.apk --arch arm64
```

I get the error:

```
I: Smaling smali folder into classes.dex...
[[edited]]/SplashActivity.smali[545,4] Invalid register: v19. Must be between v0 and v15, inclusive.
Could not smali file: [[edited]]/SplashActivity.smali
[ERROR] Try recompile the APK manually using the '--skip-recompile' option.
Traceback (most recent call last):
  File "/opt/homebrew/bin/frida-gadget", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/scripts/cli.py", line 279, in run
    run_apktool(recompile_option, str(decompiled_path.resolve()))
  File "/opt/homebrew/lib/python3.11/site-packages/scripts/cli.py", line 56, in run_apktool
    raise subprocess.CalledProcessError(process.returncode, cmd,
```

Adding ` --use-aapt2 --no-res`, as suggested by the app, didn't help.

**Comment by ksg97031** [comment]
This issue is due to an invalid register number and has been fixed in version 1.3.4 and later.
https://github.com/ksg97031/frida-gadget/blob/trunk/scripts/cli.py#L124

Thank you for your patience.
