### ISSUE TITLE
FileNotFoundError: The target class file

### ISSUE THREAD

**Issue by firaki12345-cmd** [ksg97031/frida-gadget#26]
**so i am trying to patch the latest instagram version** 

got the apk from below link (apkmirror)

[https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-361-0-0-46-88-release/instagram-361-0-0-46-88-17-android-apk-download/](url)

**Method**  
Frida-gadget

**App info**
 - Version: com.instagram.android_361.0.0.46.88-376111656_minAPI28(arm64-v8a)(360,400,420,480dpi)_apkmirror.com.apk
 - Arch: arm64-v8a

**Device info**
- Model: AC2001 (Nord_IND)
- Android Version: 10

**Logs**
```
[DEBUG] Auto-detected your frida version: 16.5.7
[DEBUG] Downloading the frida gadget library(16.5.7) for arm64
[DEBUG] Checking internet permission and extractNativeLibs settings
[DEBUG] Searching for the main activity in the smali files
Traceback (most recent call last):
  File "/home/firaki/.local/bin/frida-gadget", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/firaki/.local/lib/python3.10/site-packages/scripts/cli.py", line 341, in run
    inject_gadget_into_apk(apk_path, arch, decompiled_path, no_res, main_activity, config)
  File "/home/firaki/.local/lib/python3.10/site-packages/scripts/cli.py", line 226, in inject_gadget_into_apk
    insert_loadlibary(decompiled_path, main_activity, load_library_name)
  File "/home/firaki/.local/lib/python3.10/site-packages/scripts/cli.py", line 115, in insert_loadlibary
    raise FileNotFoundError(f"The target class file {target_smali} was not found.")
FileNotFoundError: The target class file /home/firaki/Downloads/something/com.instagram.android_361.0.0.46.88-376111656_minAPI28(arm64-v8a)(360,400,420,480dpi)_apkmirror.com/smali_classes12/com/instagram/android/activity/MainTabActivity.smali was not found.
```

**Comment by 1ikeadragon** [comment]
Command that you ran it with?

**Comment by firaki12345-cmd** [comment]
> Command that you ran it with?

I used the one given in the GitHub page

frida-gadget handtrackinggpu.apk --arch arm64 --sign

(Just ofcourse used the instagram .apk)

**Comment by 1ikeadragon** [comment]
Try manually giving it the Main activity. --main-activity <name>

**Comment by firaki12345-cmd** [comment]
> Try manually giving it the Main activity. --main-activity <name>

Thanks will try it out and will let you know.

Even tough I am not that great at java.. as I mostly know python. 

Have you tried it personally with instagram ?

**Comment by 1ikeadragon** [comment]
I just woke up. Tried it with instagram. It's not an issue with the tool but with your methodology:
```sh
frida-gadget --arch arm64 --no-res --main-activity com.instagram.mainactivity.LauncherActivity ./base.apk
```

works.

**Comment by firaki12345-cmd** [comment]
> I just woke up. Tried it with instagram. It's not an issue with the tool but with your methodology:
> 
> ```shell
> frida-gadget --arch arm64 --no-res --main-activity com.instagram.mainactivity.LauncherActivity ./base.apk
> ```
> 
> works.

hi first of all, thank you so much for your time, the latest version of instagram worked with that method, but now when i want to intercept traffic from mitmweb, it does not do it as it gets the SSl CERTIFICATE ERROR.

i tought i could bypass SSL Pin using it.

`[10:16:03.540][192.168.0.101:39972] Client TLS handshake failed. The client does not trust the proxy's certificate for graph.instagram.com (OpenSSL Error([('SSL routines', '', 'ssl/tls alert certificate unknown')]))
[10:16:03.542][192.168.0.101:39972] client disconnect
[10:16:03.543][192.168.0.101:39972] server disconnect graph.instagram.com:443 (57.144.124.192:443)
`

**using Frida Commnad Below**

**got the JS file from here below**

[https://codeshare.frida.re/@akabe1/frida-multiple-unpinning/](url)

```
`frida --device dce1e347 -N com.instagram.android -l fridascript.js [--no-pause]
     ____
    / _  |   Frida 16.5.7 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to AC2001 (id=dce1e347)

======
[#] Android Bypass for various Certificate Pinning methods [#]
======
[-] OkHTTPv3 {1} pinner not found
[-] OkHTTPv3 {2} pinner not found
[-] OkHTTPv3 {3} pinner not found
[-] OkHTTPv3 {4} pinner not found
[-] Trustkit {1} pinner not found
[-] Trustkit {2} pinner not found
[-] Trustkit {3} pinner not found
[-] Appcelerator PinningTrustManager pinner not found
[-] Fabric PinningTrustManager pinner not found
[-] OpenSSLSocketImpl Conscrypt {1} pinner not found
[-] OpenSSLSocketImpl Conscrypt {2} pinner not found
[-] OpenSSLEngineSocketImpl Conscrypt pinner not found
[-] OpenSSLSocketImpl Apache Harmony pinner not found
[-] PhoneGap sslCertificateChecker pinner not found
[-] IBM MobileFirst pinTrustedCertificatePublicKey {1} pinner not found
[-] IBM MobileFirst pinTrustedCertificatePublicKey {2} pinner not found
[-] IBM WorkLight HostNameVerifierWithCertificatePinning {1} pinner not found
[-] IBM WorkLight HostNameVerifierWithCertificatePinning {2} pinner not found
[-] IBM WorkLight HostNameVerifierWithCertificatePinning {3} pinner not found
[-] IBM WorkLight HostNameVerifierWithCertificatePinning {4} pinner not found
[-] Conscrypt CertPinManager (Legacy) pinner not found
[-] CWAC-Netsecurity CertPinManager pinner not found
[-] Worklight Androidgap WLCertificatePinningPlugin pinner not found
[-] Netty FingerprintTrustManagerFactory pinner not found
[-] Squareup CertificatePinner {1} pinner not found
[-] Squareup CertificatePinner {2} pinner not found
[-] Squareup OkHostnameVerifier check not found
[-] Squareup OkHostnameVerifier check not found
[-] Android WebViewClient {3} check not found
[-] Apache Cordova WebViewClient check not found
[-] Boye AbstractVerifier check not found
[-] Chromium Cronet pinner not found
[-] Flutter HttpCertificatePinning pinner not found
[-] Flutter SslPinningPlugin pinner not found
[AC2001::com.instagram.android ]-> [+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: i.instagram.com
[+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: i-fallback.instagram.com
[+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: scontent-bom2-4.cdninstagram.com
[+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: scontent-bom2-1.cdninstagram.com
[+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: web.facebook.com
[+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: i.instagram.com
[+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: i.instagram.com
[+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: i.instagram.com
[+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: i.instagram.com
[+] Bypassing TrustManagerImpl (Android > 7) checkTrustedRecursive check for: graph-fallback.instagram.com`
```

**Comment by firaki12345-cmd** [comment]
@1ikeadragon  ok so i also used the --sign argument and used the 336 version of instagram instead

but still could not intercept traffic

but when i patch it using the below github method, it works perfectly.

[https://github.com/Eltion/Instagram-SSL-Pinning-Bypass](url)

**Comment by firaki12345-cmd** [comment]
@1ikeadragon  OK i have finally found solution ,thanks for your time

**SOLUTION HERE:** https://github.com/Eltion/Instagram-SSL-Pinning-Bypass/issues/81
