### ISSUE TITLE
Exception: Not Found, target class file: LoginActivity.smali

### ISSUE THREAD

**Issue by Drjacky** [ksg97031/frida-gadget#6]
```bash
[DEBUG] Searching the main activity from smali files
Traceback (most recent call last):
  File "/usr/local/bin/frida-gadget", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/scripts/cli.py", line 132, in run
    raise Exception("Not Found, target class file: " + ".".join(main_activity))
Exception: Not Found, target class file: LoginActivity.smali
```

**Comment by ksg97031** [comment]
Sorry for the late reply. I need the APK file information to confirm the exact cause.
